### ISSUE TITLE
[Request] CraftTweaker Support

### ISSUE THREAD

**Issue by ghost** [ArtixAllMighty/ExSartagine#4]
It'd be great to be able to use the cooking pot, for instance, to cook a bunch of other modded food!

**Comment by AbsolemJackdaw** [comment]
no idea how to support craft tweaker.
other mods can hpwever use the sublib to add recipes from their mods 
(that stuff rarely happens though) 

I'm taking suggestions for cooking pot entries/outputs.
(we're already working on pasta and noodles)

**Comment by AbsolemJackdaw** [comment]
I'm currently adding crafttweaker support

**Comment by AbsolemJackdaw** [comment]
support added. we'll have to wait for 1.13 for a new release though
