### ISSUE TITLE
Make it possible to "exclude" specific blocks

### ISSUE THREAD

**Issue by Izbrannik** [ArtixAllMighty/ExSartagine#7]
So if someone doesn't want to have smelter or pot, he can turn them off and the excluded blocks would be not accessible

**Comment by AbsolemJackdaw** [comment]
you could use craft tweaker to edit the recipes so the blocks become unavailable . 
support for this mod is currently in suspension
blocks cannot be unregistered on the fly and need to have their recipes disabled to become unavailable without causing issues
